### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by furkanaskin** [lopspower/CircularImageView#101] opened 2019-03-24 21:07 UTC
I have a Recyclerview and i'm binding svg images to CircularImageview. When the app is running profiler was showed 200-250 MB Memory usage. First of all, i thought "SVG is using too much memory." but you know SVGs lightweight and resizable. 

Finally, i just changed my CircularImageView with ImageView and problem fixed. Now, Android Profiler is showing 60 MB memory usage in runtime.

Check SVG support for CircularImageView.

**Comment by lopspower** [comment] 2019-06-12 11:42
Duplicate of #98

**Closed by lopspower** 2019-06-12 11:42 UTC

**Comment by sagarnayak** [comment] 2019-11-11 09:40
facing same problem in the recycler view.
